[versions]
# Main
androidxKotlinVersion = "1.8.0"
ktxCoroutinesVersion = "1.6.2"
timberVersion = "5.0.1"
# Test
junitVersion = "4.13.2"
mockkVersion = "1.12.5"
androidxJUnitVersion = "1.1.3"
androidxEspressoCoreVersion = "3.4.0"

[libraries]
# Main
ktxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "ktxCoroutinesVersion" }
androidxKotlin = { module = "androidx.core:core-ktx", version.ref = "androidxKotlinVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
# Test
junit = { module = "junit:junit", version.ref = "junitVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
mockkAndroid = { module = "io.mockk:mockk-android", version.ref = "mockkVersion" }
androidxJUnit = { module = "androidx.test.ext:junit", version.ref = "androidxJUnitVersion" }
androidxEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCoreVersion" }

[bundles]
all = [
    "ktxCoroutines",
    "androidxKotlin",
    "timber",
    "junit",
    "mockk",
    "mockkAndroid",
    "androidxJUnit",
    "androidxEspressoCore"
]
androidx = [
    "androidxKotlin",
    "androidxJUnit",
    "androidxEspressoCore"
]
test = [
    "junit",
    "mockk",
    "mockkAndroid",
    "androidxJUnit",
    "androidxEspressoCore"
]